### ISSUE TITLE
gcp argument incorrectly quoted

### ISSUE THREAD

**Issue by barryrowlingson** [gearslaboratory/gdalUtils#1]
For some matrix of GCPs and some raster file names:
```
> am = matrix(100*runif(12),ncol=4)
> gdal_translate("in.tif","out.tif",gcp=am,of="GTiff",overwrite=TRUE,verbose=TRUE)
```
results in

```
ERROR 6: Too many command options 'out.tif'
```

Because the command line quotes the four parameters to each `gcp` argument:

```
GDAL command being used: "/usr/bin/gdal_translate" -gcp "31.7352093523368 47.9384476551786 17.7945003146306 43.7793212942779" -gcp "73.7488568993285 38.794300542213 9.2311471235007 93.3469131356105" -gcp "27.2829831810668 80.2421595901251 42.9110718891025 77.0867425948381" -of "GTiff" "in.tif" "out.tif"
```

When quoted like this the shell passes them as one arg to `gdal_translate` when it is expecting four after each `-gcp`.

Linux, with 
```
> packageVersion("gdalUtils")
[1] ‘2.0.1.16’
```

fresh off github.

as a related problem, if you pass a vector instead of a matrix thinking its one GCP, you get four -gcp args with one number each:

```
> gdal_translate("in.tif","out.tif",gcp=am[1,],of="GTiff",overwrite=TRUE,verbose=TRUE)
Checking gdal_installation...
Scanning for GDAL installations...
Checking the gdalUtils_gdalPath option...
GDAL version 2.2.3
GDAL command being used: "/usr/bin/gdal_translate" -gcp "31.7352093523368" -gcp "47.9384476551786" -gcp "17.7945003146306" -gcp "43.7793212942779" -of "GTiff" "in.tif" "out.tif"
```

**Comment by jgrn307** [comment]
Can you check the latest github version and let me know if that fixed it?  To clarify, the quotes need to be removed to gdal_translate right?

**Comment by jgrn307** [comment]
Barry, can you confirm the latest push works for both of the errors you reported above?

**Comment by barryrowlingson** [comment]
Yes  works now, here's my test case script:
```
library(gdalUtils)
print(packageVersion("gdalUtils"))

library(raster)

set.seed(310366)

r = raster(matrix(runif(100*100),100,100))

gcpmatrix = matrix(runif(4*3),ncol=4)

writeRaster(r,"in.tif")

gdal_translate("in.tif","out.tif",gcp=gcpmatrix,of="GTiff",overwrite=TRUE,verbose=TRUE)
gdal_translate("in.tif","out1.tif",gcp=gcpmatrix[1,],of="GTiff",overwrite=TRUE,verbose=TRUE)

gdalinfo("out.tif") # has three GCPs
gdalinfo("out1.tif") # has one GCP

# fails on data frames:
gcpdf = data.frame(gcpmatrix)
gdal_translate("in.tif","outdf.tif",gcp=gcpdf,of="GTiff",overwrite=TRUE,verbose=TRUE)
gdal_translate("in.tif","outdf1.tif",gcp=gcpdf[1,],of="GTiff",overwrite=TRUE,verbose=TRUE)

```
Not sure how best to translate above into proper test cases for `test_that` or similar...

Note that it fails if fed a data frame (documentation does say "matrix"), but running `as.matrix` on the argument would allow it to accept data frames as well.

**Comment by jgrn307** [comment]
Ok, I tweaked it to allow data.frame inputs.  I'm going to close this thread, but if the data.frame tweak didn't work, open a new thread!  Cheers!
