### ISSUE TITLE
Is this project abandoned? Should we fork?

### ISSUE THREAD

**Issue by mwip** [gearslaboratory/gdalUtils#37]
As of August 2021, the organization this repo is associated with, [gearslaboratory](https://github.com/gearslaboratory), has no (public) members, PRs are not merged, issues are not worked on, etc. 

I think this project provides high value to the geospatial R community and should be worked on. Maybe we can use this issue to discuss further development.

Any thoughts?

**Comment by mwip** [comment]
Related to https://github.com/gearslaboratory/gdalUtils/issues/32, no license or attribution can be found throughout most of the source code. Might this pose any licensing issues when forking?

**Comment by jgrn307** [comment]
Hey all, I would love it if someone would take this over, I'd be happy to have someone fork it and get it moving along again.  Feel free to contact me if you want to discuss the project status and what might need to be done.

**Comment by mwip** [comment]
I think https://github.com/JoshOBrien/gdalUtilities is the successor, we were hoping for. I'll give that a try, as I was never able to contribute in a meaningful way. Sorry.

Closing.
